spring.application.name=User-Creation

server.port=8080

spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=


spring.h2.console.enabled=true
spring.h2.console.path=/h2-console



#creating username and password and assigning the ROLE to the user
#spring.security.user.name=user
#spring.security.user.password=pass
#spring.security.user.roles=USER

#just for storing the session details in DB
#spring.session.store-type=jdbc
#spring.session.jdbc.initialize-schema=always
#server.servlet.session.timeout=5m

